### ISSUE TITLE
New release Home Assistant

### ISSUE THREAD

**Issue by Les-Glycines** [joakimjalden/frame_art#9]
Hello,

With new version home assistant this day it seems that the code has become obsolete and that the "Mode Art" function no longer works. Is there no alternative to trigger the Art mode on TV samsung ?

Thank you for your help.

**Comment by joakimjalden** [comment]
Thank you for letting me know. I waited for the weekend to update to 2025.4 myself, but will now check to see if I can repeat the error and see what it going on.

I have not tried it in myself in quite some time but I've read that the SmartThings integration has gotten a lot of love lately. Maybe that could be worth looking into. Other than that, I think that the right thing to do would be to either request the feature from the official HA integration, or even better to try to contribute it. That said, the code for the official integration was bit too complicated for me so I have yet to attempt that.

**Comment by joakimjalden** [comment]
The integration/code still works for me on HA version 2025.4.1. I can turn on art mode and the code reports the correct state. Could you describe closer what explicitly does not work for you and check the logs for error messages?

**Comment by Les-Glycines** [comment]
Hello,

Thank you for your response.

In configuration.yaml, I have : switch:
  - platform: frame_art
    switches:
      my_tv_art_mode:
        name: TV mode art
        resource: X.X.X.X

But on Home Assistant 2025.4.1, the automatisation turns on the tv directly but no longer executes the art mode function.

<img width="1292" alt="Image" src="https://github.com/user-attachments/assets/49ec10ad-6bdf-4ba2-bbcc-cafddfe03d9d" />
<img width="884" alt="Image" src="https://github.com/user-attachments/assets/c094bde1-7896-4067-9a1c-6959f79ee8aa" />

<img width="1222" alt="Image" src="https://github.com/user-attachments/assets/04fed8d0-bba9-4795-9d44-ea3e8f9a68a2" />
<img width="879" alt="Image" src="https://github.com/user-attachments/assets/6349a654-72b7-499b-a859-3c6f2c8ca20e" />

**Comment by joakimjalden** [comment]
Hi, I see your problem. The interface used to turn on art mode is unavailable when the TV is in standby mode. This is handled by making the switch unavailable when the TV is in standby mode. You can automate your way around this by checking if the switch is unavailable, turning on the TV if it is, and then setting it to art mode. Something like the following script should work.

```
sequence:
  - if:
      - condition: state
        entity_id: switch.guest_room_art
        state: unavailable
    then:
      - action: media_player.turn_on
        target:
          entity_id: media_player.guest_room_tv
      - wait_for_trigger:
          - trigger: state
            entity_id:
              - switch.guest_room_art
            from: unavailable
        timeout:
          minutes: 1
  - action: switch.turn_on
    target:
      entity_id: switch.guest_room_art
```
